# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipstercassandrasampleapplication
services:
  app:
    image: jhipstercassandrasampleapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs,secret-samples
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CASSANDRA_CONTACTPOINTS=cassandra
      - JHIPSTER_SLEEP=10
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD-SHELL
        - "bash -c 'exec 3<>/dev/tcp/127.0.0.1/8080; printf \"GET
          /management/health HTTP/1.0\\r\\nHost: localhost\\r\\n\\r\\n\" >&3;
          grep -q \"\\\"status\\\":\\\"UP\\\"\" <&3'"
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      cassandra:
        condition: service_healthy
      cassandra-migration:
        condition: service_completed_successfully
  cassandra:
    extends:
      file: ./cassandra.yml
      service: cassandra
  cassandra-migration:
    extends:
      file: ./cassandra.yml
      service: cassandra-migration
