# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipstercassandrasampleapplication
services:
  cassandra:
    extends:
      file: ./cassandra.yml
      service: cassandra
  cassandra-migration:
    extends:
      file: ./cassandra.yml
      service: cassandra-migration
